#The purpose of this file is to link EC2 instances with Ansible groups
tag_Name_dev_app:

tag_Name_dev_esb:

app_servers:
  children:
    tag_Name_dev_app:

esb_servers:
  children:
    tag_Name_dev_esb:

#Logical grouping of all the servers which are part of the same platform
dragon_cloud_servers:
  children:
    app_servers:
    esb_servers:

windows_servers:
  children:
    dragon_cloud_servers:
